// StateLogger/Sources/SimToolStateLogger/StateReportable.swift
import Foundation

/// A value whose state can be expanded into a SimTool snapshot. Conformance is
/// generated by the `@SimToolDebugState` macro; do not implement by hand in app
/// code. Structs conform to this protocol directly; classes conform via
/// `SimToolStateReportable`.
///
/// The requirement is `@MainActor` (not the whole protocol) so conforming types
/// do not become implicitly main-actor-isolated, while `@MainActor` model
/// classes can still satisfy it.
public protocol SimToolStateExpandable {
    @MainActor
    func _simToolSnapshot(visited: inout Set<ObjectIdentifier>) -> SimToolStateValue
}

/// A class whose instances can be tracked by `SimToolState` (the tracker holds
/// them weakly, hence `AnyObject`).
public protocol SimToolStateReportable: SimToolStateExpandable, AnyObject {}

extension SimToolStateExpandable {
    @MainActor
    public func _simToolSnapshot() -> SimToolStateValue {
        var visited: Set<ObjectIdentifier> = []
        return _simToolSnapshot(visited: &visited)
    }
}

/// Generates a snapshot conformance: classes get `SimToolStateReportable`
/// (trackable via `SimToolState.track`), structs get `SimToolStateExpandable`
/// (expand when nested in a tracked model). The generated `_simToolSnapshot`
/// reads every stored property through its accessor, which lets observation
/// tracking detect changes in `@Observable` classes; plain classes are tracked
/// by polling (see `SimToolState.track(_:name:poll:)`).
@attached(member, names: named(_simToolSnapshot))
@attached(extension, conformances: SimToolStateReportable, SimToolStateExpandable)
public macro SimToolDebugState() =
    #externalMacro(module: "SimToolStateLoggerMacros", type: "SimToolDebugStateMacro")
